# Generated by Django 5.0.2 on 2024-03-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alert_dashboard_feedback_responsefromadmin_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
    ]
