# Generated by Django 5.0.2 on 2024-03-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alert_dashboard_feedback_responsefromadmin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
