# Generated by Django 5.0.2 on 2024-03-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_userprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
