# Generated by Django 5.0.2 on 2024-04-01 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="station_data",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="user",
        ),
        migrations.AddField(
            model_name="alert",
            name="station",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.weatherstation",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="alert_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="alert",
            name="message",
            field=models.TextField(),
        ),
    ]
